version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  logstash-indexer:
    container_name: logstash-indexer
    image: docker.elastic.co/logstash/logstash:7.1.1
    volumes:
      - ./logstash-indexer.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:5601 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3
  
  nginx-auth:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    container_name: nginx-auth
    ports:
      - 8080:80
    networks: 
      - logging-network
    links:
      - kibana
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - PROXY_PASS=http://kibana:5601/

  redis-broker:
    image: redis:latest
    container_name: redis-broker
    ports:
      - 6379:6379
    networks:
      - logging-network
    restart: always

networks:
  logging-network:
    driver: bridge
    name: logging-network
