version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - united-network
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  logstash-indexer:
    container_name: logstash-indexer
    image: docker.elastic.co/logstash/logstash:7.1.1
    volumes:
      - ./logstash-indexer.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - united-network
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    networks:
      - united-network
    healthcheck:
      test: curl --fail http://localhost:5601 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  nginx-proxy:
    image: nginx:1.17.6
    container_name: nginx-proxy
    networks:
      - united-network
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd_kibana:/etc/nginx/.htpasswd_kibana
      - ./nginx/.htpasswd_prometheus:/etc/nginx/.htpasswd_prometheus
    logging:
      driver: gelf
      options:
        gelf-address: "udp://35.172.100.128:12201"
        tag: "nginx-proxy"

  redis-broker:
    image: redis:latest
    container_name: redis-broker
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - united-network
    restart: always

  elasticsearch-curator:
    image: elasticsearch-curator:0.0.0
    container_name: curator
    volumes:
      - ./Curator:/etc/curator
    networks:
      - united-network
    restart: always
    tty: true

networks:
  united-network:
    name: united-network
    driver: bridge
