version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    depends_on:
      - logstash
    networks:
      - logging-network
    healthcheck:
      test: curl --fail http://localhost:5601 || exit 1
      interval: 600s
      timeout: 10s
      retries: 3
  
  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8080:80
    networks: 
      - logging-network
    links:
      - kibana
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - PROXY_PASS=http://kibana:5601/


networks:
  logging-network:
    driver: bridge
